import BasicMigration from '../app/modules/migrate/components/basicMigration';
import {grantAccess} from '../app/modules/authorization/utils';

export default class Migration extends BasicMigration {
	constructor() {
		super();

		this.applyToSample = true;
		this.applyToWrapper = false;
		this.applyToInstances = true;
	}

	async up(db, type, instanceRegistry = null) {
		await db.sql(`
			create table if not exists email_tpl (
				id integer primary key generated by default as identity,
				title varchar(255) not null,
				alias varchar(255) not null unique,
				subject text,
				template text not null,
				created_at timestamp with time zone not null default now()
			)
		`);

		await db.sql(`
			insert into email_tpl
				(title, alias, template, subject)
			values
				(:title, :alias, :template, :subject)
			on conflict do nothing
		`, {
			title: 'Password restore',
			alias: 'auth.passwordRestore',
			subject: 'Password restore',
			template: `<h3>Hello {{username}},</h3>
<p>We heard you need a password reset. Click the link below and you'll be redirected to a secure site from which you can set a new password.</p>
<p style="text-align: center">
	<a href="{{restoreUrl}}" class="cta-btn" target="_blank">Reset password</a>
</p>
<p>If you did not request a password reset, please ignore this email.</p>`
		});

		await db.sql(`
			insert into email_tpl
				(title, alias, template, subject)
			values
				(:title, :alias, :template, :subject)
			on conflict do nothing
		`, {
			title: 'Welcome email',
			alias: 'customer.welcomeEmail',
			subject: 'Welcome!',
			template: `<h2 class="text-center">
	{{#firstName}}
		{{firstName}}, thank you for the registration!
	{{/firstName}}
	{{^firstName}}
		Thank you for the registration!
	{{/firstName}}
</h2>
{{#email}}
	{{#pass}}
		<br/>
		<p><b>Your Credentials:</b></p>
		<p>
			Email: {{email}} <br/>
			Your password: {{pass}}
		</p>
	{{/pass}}
{{/email}}
{{#loginUrl}}
	<p class="text-center">
		<a href="{{loginUrl}}" class="cta-btn" target="_blank">Sign In!</a>
	</p>
{{/loginUrl}}
`
		});

		await db.sql(`
			update notification_template
			set
				template = :template
			where
				event_type = :created
				and transport = :email
				and status_id is null
		`, {
			created: 'created',
			email: 'email',
			template: `<h1 class="text-center">Thank you for your order!</h1>
<p>Your order id is <b>#{{ORDER_ID}}</b>.</p>
<p class="text-center">
	<a href="{{ORDER_URL}}" alt="Order link" target="_blank" class="cta-btn">View order</a>
</p>
<table class="table table-bordered table-hover table-striped">
	<thead>
		<tr>
			<th class="item"></th>
			<th class="price">Price</th>
			<th class="qty">Qty</th>
			<th class="total">Total</th>
		</tr>
	</thead>
	<tbody>
		{{#ITEMS}}
			<tr data-item="{{item_id}}">
				<td class="item">
					<a class="img" href="{{product.url}}" target="_blank">
						{{#image.src}}
							<img src="{{image.src}}" alt="{{title}}" />
						{{/image.src}}
						{{^image}}
							<div class="no-image" style="width:100px;height:100px;"></div>
						{{/image}}
					</a>
					<div class="desc">
						<p>
							{{#isCustomItem}}
								{{custom_item.title}}
							{{/isCustomItem}}
							{{^isCustomItem}}
								<a href="{{product.url}}" target="_blank">{{product.title}}</a>
							{{/isCustomItem}}
						</p>
						{{#isVariant}}
							<p class="small">{{variant.title}}</p>
						{{/isVariant}}
						{{#sku}}
							<p class="small">SKU: {{sku}}</p>
						{{/sku}}
					</div>
				</td>
				<td class="price">{{final_price_formatted}}</td>
				<td class="qty">{{qty}}</td>
				<td class="total">{{total_price_formatted}}</td>
			</tr>
		{{/ITEMS}}
	</tbody>
	<tfoot>
		<tr class="items-total info">
			<th colspan="2" class="title">Total:</th>
			<th class="qty text-center">{{SUMMARY.total_qty}}</th>
			<th class="total">{{SUMMARY.subtotal_price_formatted}}</th>
		</tr>
		{{#DISCOUNTS.length}}
			<tr>
				<th colspan="4" class="bg-blue">Discount</th>
			</tr>
			<tr>
				<td colspan="3">
					{{#DISCOUNTS}}
						{{#isManualSource}}
							<p>{{title}} - <strong>{{value_formatted}}</strong></p>
						{{/isManualSource}}
					{{/DISCOUNTS}}
				</td>
				<td class="total">-{{SUMMARY.discount_for_order_formatted}}</td>
			</tr>
		{{/DISCOUNTS.length}}
		{{#SHIPPING}}
			<tr>
				<th colspan="4" class="bg-blue">Shipping</th>
			</tr>
			<tr>
				<td colspan="3" class="title">
					<p>{{SHIPPING.title}}</p>
					{{#SHIPPING.text_info}}
						<p class="text-muted"><em>{{shipping.text_info}}</em></p>
					{{/SHIPPING.text_info}}
					<div class="address-row">
						<p>
							{{SHIPPING_ADDRESS.name}}
							{{#CUSTOMER.personProfile.phone}}
								<br/>Tel: {{CUSTOMER.personProfile.phone}}
							{{/CUSTOMER.personProfile.phone}}
						</p>
						{{#SHIPPING_ADDRESS}}
							{{#company}}<div>{{company}}</div>{{/company}}
							{{#address_line_1}}<div>{{address_line_1}}</div>{{/address_line_1}}
							{{#address_line_2}}<div>{{address_line_2}}</div>{{/address_line_2}}
							{{#city_with_country}}<div>{{city_with_country}}</div>{{/city_with_country}}
							{{#zip}}<div>{{zip}}</div>{{/zip}}
						{{/SHIPPING_ADDRESS}}
					</div>
				</td>
				<td class="total text-center">{{SHIPPING.price_formatted}}</td>
			</tr>
		{{/SHIPPING}}
		{{#PAYMENT_METHOD}}
			<tr>
				<th colspan="4" class="bg-blue">Payment method</th>
			</tr>
			<tr>
				<td colspan="3" class="title">
					<div>{{title}}</div>
					{{#hasMarkUp}}<div style="margin-top:5px">Payment markup ({{mark_up}}%)</div>{{/hasMarkUp}}
				</td>
				<td class="total text-center">
					{{#hasMarkUp}}{{ORDER.payment_mark_up_formatted}}{{/hasMarkUp}}
				</td>
			</tr>
		{{/PAYMENT_METHOD}}
		{{#TAX_SETTINGS.turnedOn}}
			<tr>
				<th colspan="3" class="bg-blue text-right">{{TAX_SETTINGS.taxTitle}}:</th>
				<th class="bg-blue text-center">{{ORDER.tax_amount_formatted}}</th>
			</tr>
		{{/TAX_SETTINGS.turnedOn}}
		<tr class="order-total info">
			<th colspan="2" class="title">Total:</th>
			<th class="qty text-center">{{SUMMARY.total_qty}}</th>
			<th class="total">{{SUMMARY.total_price_formatted}}</th>
		</tr>
	</tfoot>
</table>
{{#ORDER.orderProp.client_comment}}
	<p class="client-comment">{{ORDER.orderProp.client_comment}}</p>
{{/ORDER.orderProp.client_comment}}
`
			});

		await db.sql(`
			insert into email_tpl
				(title, alias, template, subject)
			values
				(:title, :alias, :template, :subject)
			on conflict do nothing
		`, {
			title: 'Notification for Admins about the New order',
			alias: 'orders.newOrderAdmin',
			subject: 'New order #{{ORDER_ID}}',
			template: `<h1>New order #{{ORDER_ID}}</h1>
<p>
	<b>Date:</b> {{ORDER.created_at_formatted_long}}
</p>
<p class="text-center">
	<a href="{{ADMIN_ORDER_URL}}" alt="Order link" target="_blank" class="cta-btn">Manage order</a>
</p>
<table class="table table-bordered table-hover table-striped">
	<thead>
		<tr>
			<th class="item"></th>
			<th class="price">Price</th>
			<th class="qty">Qty</th>
			<th class="total">Total</th>
		</tr>
	</thead>
	<tbody>
		{{#ITEMS}}
			<tr data-item="{{item_id}}">
				<td class="item">
					<a class="img" href="{{product.url}}" target="_blank">
						{{#image.src}}
							<img src="{{image.src}}" alt="{{title}}"/>
						{{/image.src}}
						{{^image}}
							<div class="no-image" style="width:100px;height:100px;"></div>
						{{/image}}
					</a>
					<div class="desc">
						<p>
							{{#isCustomItem}}
								{{custom_item.title}}
							{{/isCustomItem}}
							{{^isCustomItem}}
								<a href="{{product.url}}" target="_blank">{{product.title}}</a>
							{{/isCustomItem}}
						</p>
						{{#isVariant}}
							<p class="small">{{variant.title}}</p>
						{{/isVariant}}
						{{#sku}}
							<p class="small">SKU: {{sku}}</p>
						{{/sku}}
					</div>
				</td>
				<td class="price">
					{{final_price_formatted}}
				</td>
				<td class="qty">{{qty}}</td>
				<td class="total">
					{{total_price_formatted}}
				</td>
			</tr>
		{{/ITEMS}}
	</tbody>
	<tfoot>
		<tr class="items-total info">
			<th colspan="2" class="title">Total:</th>
			<th class="qty text-center">{{SUMMARY.total_qty}}</th>
			<th class="total">
				{{SUMMARY.subtotal_price_formatted}}
			</th>
		</tr>
		{{#DISCOUNTS.length}}
			<tr>
				<th colspan="4" class="bg-blue">Discount</th>
			</tr>
			<tr>
				<td colspan="3">
					{{#DISCOUNTS}}
						{{#isManualSource}}
							<p>
							{{title}} - <strong>{{value_formatted}}</strong>
							</p>
						{{/isManualSource}}
					{{/DISCOUNTS}}
				</td>
				<td class="total">-{{SUMMARY.discount_for_order_formatted}}</td>
			</tr>
		{{/DISCOUNTS.length}}
		{{#SHIPPING}}
			<tr>
				<th colspan="4" class="bg-blue">Shipping</th>
			</tr>
			<tr>
				<td colspan="3" class="title">
					<p>{{SHIPPING.title}}</p>
					{{#SHIPPING.text_info}}
						<p class="text-muted">
							<em>{{shipping.text_info}}</em>
						</p>
					{{/SHIPPING.text_info}}
					<div class="address-row">
						<p>
							{{SHIPPING_ADDRESS.name}}
							{{#CUSTOMER.personProfile.phone}}
							<br/>Tel: {{CUSTOMER.personProfile.phone}}{{/CUSTOMER.personProfile.phone}}
						</p>
						{{#SHIPPING_ADDRESS}}
							{{#company}}<div>{{company}}</div>{{/company}}
							{{#address_line_1}}<div>{{address_line_1}}</div>{{/address_line_1}}
							{{#address_line_2}}<div>{{address_line_2}}</div>{{/address_line_2}}
							{{#city_with_country}}<div>{{city_with_country}}</div>{{/city_with_country}}
							{{#zip}}<div>{{zip}}</div>{{/zip}}
						{{/SHIPPING_ADDRESS}}
					</div>
				</td>
				<td class="total text-center">{{SHIPPING.price_formatted}}</td>
			</tr>
		{{/SHIPPING}}
		{{#PAYMENT_METHOD}}
			<tr>
				<th colspan="4" class="bg-blue">Payment method</th>
			</tr>
			<tr>
				<td colspan="3" class="title">
					<div>{{title}}</div>
					{{#hasMarkUp}}
						<div style="margin-top:5px">Payment markup ({{mark_up}}%)</div>
					{{/hasMarkUp}}
				</td>
				<td class="total text-center">
					{{#hasMarkUp}}
						{{ORDER.payment_mark_up_formatted}}
					{{/hasMarkUp}}
				</td>
			</tr>
		{{/PAYMENT_METHOD}}
		{{#TAX_SETTINGS.turnedOn}}
			<tr>
				<th colspan="3" class="bg-blue text-right">{{TAX_SETTINGS.taxTitle}}:</th>
				<th class="bg-blue text-center">{{ORDER.tax_amount_formatted}}</th>
			</tr>
		{{/TAX_SETTINGS.turnedOn}}
		<tr class="order-total info">
			<th colspan="2" class="title">Total:</th>
			<th class="qty text-center">{{SUMMARY.total_qty}}</th>
			<th class="total">{{SUMMARY.total_price_formatted}}</th>
		</tr>
	</tfoot>
</table>
{{#ORDER.orderProp.client_comment}}
	<p class="client-comment">{{ORDER.orderProp.client_comment}}</p>
{{/ORDER.orderProp.client_comment}}
{{#CUSTOMER}}
	<div>
		<h3>Customer info</h3>
		<p>
			#{{CUSTOMER.person_id}}, {{CUSTOMER_FULLNAME}} (<a href="{{CUSTOMER_FORM_URL}}" target="_blank">Edit customer</a>)
		</p>
		<p>
			{{#CUSTOMER.personProfile.phone}}
				tel: <a href="tel:{{CUSTOMER.personProfile.phone}}">{{CUSTOMER.personProfile.phone}}</a>,
			{{/CUSTOMER.personProfile.phone}}
			email: <a href="mailto:{{CUSTOMER.email}}">{{CUSTOMER.email}}</a>
		</p>
	</div>
{{/CUSTOMER}}
<hr class="hr-thin" />`
		});

		const [row] = await db.sql(`
			select * from setting where setting_group = 'system' and key = 'locale'
		`);

		if (!instanceRegistry || row.value.phone.mask == 'P0X (000) 000-0000XXXX') {
			const value = Object.assign(row.value, {
				phone: {
					mask: null,
					placeholder: '+1(555)123-4567'
				}
			});

			await db.sql('update setting set value = :value where setting_id = :id', {
				value: JSON.stringify(value),
				id: row.setting_id
			});
		}

		await this.grantPrivileges(db, instanceRegistry);
		await grantAccess(db, 'admin', 'system:admin:emailTpls');
	}
}