const pathAlias = require('path-alias');

let filesList = [
	'node_modules/backbone-checkbox-list/lib/backbone-checkbox-list',
	'node_modules/backbone-labels-list/lib/backbone-labels-list',
	'node_modules/backgrid/lib/backgrid',
	'node_modules/backgrid-paginator/backgrid-paginator',
	'node_modules/backbone-tree-model/src/backbone.treemodel',
	'node_modules/backbone-tree-view/lib/backbone-tree-view',

	/* grid */,
	'@modules/grid/views/commonFilter.@c',
	'@modules/grid/views/html.@c',
	'@modules/grid/views/html/backgrid.@c',
	'@modules/grid/views/html/bulkButtons.@c',
	'@modules/grid/views/html/backgrid/buttonsCell.@c',
	'@modules/grid/views/html/backgrid/filterRow.@c',
	'@modules/grid/views/html/backgrid/bulk/checkboxCell.@c',
	'@modules/grid/views/html/backgrid/bulk/selectAllCell.@c',
	'@modules/grid/views/html/commonButtons.@c',
	'@p-system/widgets/grid.@c',

	'@modules/widget/treeWidget.@c',

	/* system package: */
	'@p-system/widgets/adminMenu.@c',
	'@p-system/widgets/webhookForm.@c',
	'@p-system/widgets/webhookGrid.@c',

	/* auth package: */
	'@p-auth/vue/admin/Tokens',
	'@p-auth/vue/admin/tokens/TokenEdit',
	'@p-auth/vue/admin/tokens/TokenCreate',
	'@p-auth/widgets/tokenGrid.@c',
	'@p-auth/widgets/usersGrid.@c',

	/* catalog package: */
	'@p-catalog/widgets/addFilterFieldForm.@c',
	'@p-catalog/widgets/adminFilterFields.@c',
	'@p-catalog/widgets/filterGrid.@c',
	'@p-catalog/widgets/productGrid.@c',
	'@p-catalog/widgets/serviceGrid.@c',
	'@p-catalog/widgets/settingsSortForm.@c',
	'@p-catalog/widgets/manufacturerGrid.@c',
	'@p-catalog/widgets/adminManufacturerLogo.@c',
	'@p-catalog/widgets/commodityGroupGrid.@c',
	'@p-catalog/widgets/characteristicGrid.@c',
	'@p-catalog/widgets/characteristicForm.@c',
	'@p-catalog/widgets/categoryTree.@c',
	'@p-catalog/widgets/categoryFormTab.@c',
	'@p-catalog/widgets/categoryFormPropTab.@c',
	'@p-catalog/widgets/categoryTree/itemView.@c',
	'@p-catalog/widgets/variantGrid.@c',
	'@p-catalog/widgets/collectionGrid.@c',
	'@p-catalog/widgets/collectionProductsList.@c',
	'@p-catalog/widgets/productQtyHistoryGrid.@c',
	'@p-catalog/widgets/importInProcess.@c',
	'@p-catalog/widgets/importTableSetupForm.@c',
	'@p-catalog/widgets/importUploader.@c',
	'@p-catalog/widgets/importByUrlForm.@c',
	'@p-catalog/widgets/importResultsGrid.@c',
	'@p-catalog/widgets/importScheduleGrid.@c',
	'@p-catalog/widgets/labelColorForm.@c',
	'@p-catalog/widgets/labelRemoveAfter.@c',
	'@p-catalog/widgets/labelGrid.@c',
	'@p-catalog/widgets/collectionProductForm.@c',
	'@p-catalog/widgets/categoryInlineForm.@c',
	'@p-catalog/widgets/categorySortProducts.@c',
	'@p-catalog/widgets/productReviewsGrid.@c',
	'@p-catalog/widgets/productImgForm.@c',
	'@p-catalog/widgets/manufacturerForm.@c',
	'@p-catalog/widgets/toBasketVariants.@c',
	'@p-catalog/vue/admin/manufacturer/Title',

	//product widgets
	'@p-catalog/vue/admin/product/export/Form',
	'@p-catalog/vue/admin/product/review/ProductsReviewForm',

	'@p-catalog/vue/admin/product/form/components/Variants/SetPrices',
	'@p-catalog/vue/admin/product/form/components/Variants/SetQty',
	'@p-catalog/vue/admin/product/form/components/CreateMultipleVariantsForm',
	'@p-catalog/vue/admin/product/form/components/CreateMultipleVariantsForm/Variants',
	'@p-catalog/vue/admin/product/form/components/ProductForm/VariantsTab/Size',
	'@p-catalog/vue/admin/product/form/components/ProductForm/VariantsTab/Variants/EditQty',
	'@p-catalog/vue/admin/product/form/components/ProductForm/VariantsTab/Variants/EditPrice',
	'@p-catalog/vue/admin/product/form/components/ProductForm/VariantsTab/GroupAndCharacteristics/GroupForm',
	'@p-catalog/vue/admin/product/form/components/ProductForm/VariantsTab/GroupAndCharacteristics/Characteristics',
	'@p-catalog/vue/admin/product/form/components/ProductForm/VariantsTab/GroupAndCharacteristics',
	'@p-catalog/vue/admin/product/form/components/ProductForm/VariantsTab/Props',
	'@p-catalog/vue/admin/product/form/components/ProductForm/VariantsTab/Variants',
	'@p-catalog/vue/admin/product/form/components/ProductForm/AdditionsTab',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab',
	'@p-catalog/vue/admin/product/form/components/ProductForm/AdditionsTab/Yml',
	'@p-catalog/vue/admin/product/form/components/ProductForm/AdditionsTab/CrossSell',
	'@p-catalog/vue/admin/product/form/components/ProductForm/AdditionsTab/CrossSell/Category',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab/Category',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab/StockAndPrice',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab/Seo',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab/Label',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab/StockAndPrice/PriceRow',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab/StockAndPrice/Stock',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab/StockAndPrice/Stock/AvailableRow',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab/StockAndPrice/Stock/QtyRow',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab/Images',
	'@p-catalog/vue/admin/product/form/components/ProductForm/ProductTab/Collections',
	'@p-catalog/vue/admin/product/form/components/ProductForm/VariantsTab',
	'@p-catalog/vue/admin/product/form/components/ProductTabs',
	'@p-catalog/vue/admin/product/form/components/ProductForm',
	'@p-catalog/vue/admin/product/form/components/TopNav/Buttons',
	'@p-catalog/vue/admin/product/form/components/TopNav/SaveButton',
	'@p-catalog/vue/admin/product/form/components/VariantForm',
	'@p-catalog/vue/admin/product/form/components/SimpleForm',
	'@p-catalog/vue/admin/product/form/components/FindCrossSellForm',
	'@p-catalog/vue/admin/product/form/components/TopNav',


	'@p-cms/widgets/adminImageList.@c',
	'@p-cms/widgets/adminTypeArea.@c',
	'@p-cms/widgets/basicPageRel.@c',
	'@p-cms/widgets/categoryMenuRel.@c',
	'@p-cms/widgets/imageManager.@c',
	'@p-cms/widgets/imageResizeForm.@c',
	'@p-cms/widgets/menuItemForm.@c',
	'@p-cms/widgets/menuItemForm/productRel.@c',
	'@p-cms/widgets/menuItemTree.@c',
	'@p-cms/widgets/menuItemTree/itemView.@c',
	'@p-cms/widgets/menuItemTree/itemViewSimple.@c',
	'@p-cms/widgets/pageTree/itemView.@c',
	'@p-cms/widgets/pageTree.@c',
	'@p-cms/widgets/typeArea/basic.@c',
	'@p-cms/widgets/typeArea/text.@c',
	'@p-cms/widgets/pageMenuRel.@c',
	'@p-cms/widgets/pageMenuRel.@c',
	'@p-cms/widgets/articleForm.@c',
	'@p-cms/widgets/articlesGrid.@c',
	'@p-cms/widgets/pageFormTab.@c',
	'@p-cms/widgets/menuItemTreeSimple.@c',
	'@p-cms/widgets/faviconForm.@c',
	'@p-cms/widgets/menu.@c',
	'@p-cms/vue/image/ImageUploader',

	'@p-customer/widgets/customerForm.@c',
	'@p-customer/vue/customerForm/formBody.@c',
	'@p-customer/widgets/customerGrid.@c',
	'@p-customer/widgets/customerGroupGrid.@c',
	'@p-customer/widgets/addressForm.@c',
	'@p-customer/vue/admin/attribute/Form',
	'@p-customer/vue/admin/customerForm/CustomerForm',
	'@p-customer/vue/admin/customerForm/store',
	'@p-customer/vue/admin/customerForm/Buttons/SaveButton',
	'@p-customer/vue/admin/customerForm/Tabs/AddressesTab',
	'@p-customer/vue/admin/customerForm/Tabs/AddressesTab/AddressItem',
	'@p-customer/vue/admin/customerForm/Tabs/AttributesTab',
	'@p-customer/vue/admin/customerForm/Tabs/CustomerTab',
	'@p-customer/vue/admin/customerForm/Tabs/OrdersTab',

	'@p-inventory/widgets/changeQtyGrid.@c',
	'@p-inventory/widgets/optionChangeQtyGrid.@c',
	'@p-inventory/widgets/optionGrid.@c',
	'@p-inventory/widgets/qtyDiff.@c',
	'@p-inventory/widgets/warehouseGrid.@c',
	'@p-inventory/widgets/movementInfoGrid.@c',
	'@p-inventory/widgets/stockPerWarehouseGrid.@c',
	'@p-inventory/widgets/stockPerWarehouseGrid/footer.@c',
	'@p-inventory/widgets/warehouseMovementForm.@c',
	'@p-inventory/widgets/warehouseMovementsGrid.@c',
	'@p-inventory/modals/chooseProductVariant.@c',

	'@p-orders/widgets/adminOrderItemsGrid/footer.@c',
	'@p-orders/widgets/adminOrderItemsGrid/shippingRow.@c',
	'@p-orders/widgets/adminOrderItemsGrid/discountRow.@c',
	'@p-orders/widgets/adminOrderItemsGrid/paymentRow.@c',
	'@p-orders/widgets/adminOrderItemsGrid/servicesSummaryRow.@c',
	'@p-orders/widgets/adminOrderItemsGrid.@c',
	'@p-orders/widgets/deliveryForm.@c',
	'@p-orders/widgets/itemsForm.@c',
	'@p-orders/widgets/orderBBViews/chooseCustomer.@c',
	'@p-orders/widgets/orderBBViews/chooseShippingMethod.@c',
	'@p-orders/widgets/orderBBViews/services.@c',
	'@p-orders/widgets/orderBBViews/serviceItem.@c',
	'@p-orders/widgets/ordersGrid.@c',
	'@p-orders/widgets/specifyWarehouseForm.@c',
	'@p-orders/widgets/trackNumberForm.@c',
	'@p-orders/widgets/deliveryGrid.@c',
	'@p-orders/widgets/chooseWhatToPrint.@c',
	'@p-orders/widgets/chooseWhatToPrintList.@c',
	'@p-orders/widgets/createPaymentMethodForm.@c',
	'@p-orders/widgets/deliveryBoxGrid.@c',
	'@p-orders/widgets/smsSettingsForm.@c',
	'@p-orders/widgets/deliveryCdekForm.@c',
	'@p-orders/widgets/orderSettingsForm.@c',
	'@p-orders/widgets/couponCodesGrid.@c',
	'@p-orders/widgets/couponForm.@c',
	'@p-orders/widgets/couponForm/Form',
	'@p-orders/vue/orderSettings/index.@c',
	'@p-orders/modals/choosePickupPoint.@c',
	'@p-orders/widgets/orderStatusColorForm.@c',
	'@p-orders/vue/admin/order/form/OrderForm',
	'@p-orders/vue/admin/order/form/store',
	'@p-orders/vue/admin/order/form/AttributesForm/AttributesTab/AttributesList',
	'@p-orders/vue/admin/order/form/AttributesForm/AttributesTab/TrackingNumbers',
	'@p-orders/vue/admin/order/form/AttributesForm/AttributesTab/AttributesList/TextInput',
	'@p-orders/vue/admin/order/form/AttributesForm/AttributesTab/AttributesList/CheckBoxInput',
	'@p-orders/vue/admin/order/form/AttributesForm/AttributesTab/AttributesList/SelectInput',
	'@p-orders/vue/admin/order/form/AttributesForm/AttributesTab/AttributesList/TextAreaInput',
	'@p-orders/vue/admin/order/form/AttributesForm/AttributesTab',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/TotalForm',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/StatusForm',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/DiscountsForm',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/ProductsList/ProductsList',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/ProductsList/ProductItem',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/ProductsList/Subtotal',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/ProductsForm',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/ShippingForm',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/CustomerForm/AddressItem',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/CustomerForm/CustomerSearch',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab/CustomerForm',
	'@p-orders/vue/admin/order/form/OrderForm/OrderTab',
	'@p-orders/vue/admin/order/form/TopNav/Buttons',
	'@p-orders/vue/admin/order/form/TopNav/SaveButton',
	'@p-orders/vue/admin/order/form/TopNav',
	'@p-orders/vue/admin/order/form/OrderTabs',
	'@p-orders/vue/admin/order/attribute/Form/AttributeForm',
	'@p-orders/vue/admin/order/attribute/Form',
	'@p-orders/vue/admin/order/itemPrice/ItemPriceForm',
	'@p-orders/vue/admin/order/shipping/Form',
	'@p-orders/vue/admin/order/checkout/Form',
	'@p-orders/vue/admin/order/discount/Form',
	'@p-orders/vue/admin/order/addProducts/AddProductsForm/SummaryAdding',
	'@p-orders/vue/admin/order/addProducts/AddProductsForm/Products/Price',
	'@p-orders/vue/admin/order/addProducts/AddProductsForm/Products/2BasketQty',
	'@p-orders/vue/admin/order/addProducts/AddProductsForm/Products',
	'@p-orders/vue/admin/order/addProducts/AddProductsForm/Categories',
	'@p-orders/vue/admin/order/addProducts/AddProductsForm',
	'@p-orders/vue/admin/order/trackNumber/Form',
	'@p-orders/vue/admin/order/customItem/CustomItemForm',
	'@p-orders/vue/admin/order/customer/Form',
	'@p-orders/vue/admin/setup/NotificationsForm',
	'@p-orders/widgets/order.@c',
	'@p-orders/widgets/emailNotificationForm.@c',
	'@p-orders/widgets/addressByTypeForm.@c',
	'@p-orders/widgets/orderStatusGrid.@c',

	'@p-dashboard/vue/admin/SalesOverTime',
	'@p-dashboard/vue/admin/SalesOverTime/Chart',

	'@p-system/widgets/domainWidget.@c',

	'@p-payment/widgets/adminGrid.@c',
	'@p-payment/widgets/basicPaymentForm.@c',
	'@p-payment/widgets/createPaymentMethodForm.@c',
	'@p-payment/widgets/paypalPaymentForm.@c',

	/* bulk buttons */
	'@modules/bulkButtons/kit.@c',
	'@p-system/widgets/bulkButtons.@c',
	'@p-system/widgets/filter.@c',
	'@p-system/widgets/openGraphImage.@c',
	'@p-system/widgets/switcherBar.@c',
	'@p-system/widgets/adminComment.@c',

	'@p-system/vue/admin/SelliosAccount',
	'@p-system/vue/admin/Locale',

	// '@p-theme/widgets/faviconForm.@c',
	'@p-theme/vue/link/FindAndInsert',
	'@p-theme/vue/link/FindAndInsert/Category',
	'@p-theme/vue/link/FindAndInsert/Email',
	'@p-theme/vue/link/FindAndInsert/Page',
	'@p-theme/vue/link/FindAndInsert/Phone',
	'@p-theme/vue/link/FindAndInsert/Product',
	'@p-theme/vue/link/FindAndInsert/Telegram',
	'@p-theme/vue/link/FindAndInsert/WhatsApp',

	'@p-cms/widgets/formGrid.@c',

	'@p-system/modules/urlGenerator.@c',
	'@p-system/modules/intercom.@c',

	'@p-system/vue/admin/SeoTpl',
	'@p-system/widgets/organizationImages.@c',

	'@p-cms/vue/admin/IconWithLink',
];

[
	'theme',
	'productAdmin',
	'categoryForm'
].forEach((fileName) => {
	filesList = filesList.concat(require(`./admin/${fileName}`));
});

filesList = filesList.map((filePath) => {
	return pathAlias.resolve(filePath);
});

module.exports = filesList;