module.exports = [
	'node_modules/codemirror/lib/codemirror',
	// 'node_modules/codemirror/mode/css/css',
	// 'node_modules/codemirror/mode/javascript/javascript',
	// 'node_modules/codemirror/mode/markdown/markdown',
	'node_modules/codemirror/mode/xml/xml',
	// 'node_modules/codemirror/mode/meta',
	'node_modules/codemirror/mode/htmlmixed/htmlmixed',
	'node_modules/codemirror/mode/handlebars/handlebars',
	'node_modules/codemirror/mode/mathematica/mathematica',
	'node_modules/codemirror/addon/display/placeholder',
	// 'node_modules/codemirror/addon/selection/active-line',
	'node_modules/codemirror/addon/mode/simple',
	'node_modules/codemirror/addon/mode/multiplex',
	// 'app/vendors/jade-code-mirror/index',
]