name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Admin
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        file: ./.docker/node.Dockerfile
        push: true
        target: main-node
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/boundless-commerce-admin:latest

    - name: Build and push Admin-Static
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        file: ./.docker/node.Dockerfile
        push: true
        target: nginx-static
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/boundless-commerce-admin-static:latest

    - name: Build and push Events-Listener
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        file: ./.docker/node.Dockerfile
        push: true
        target: event-server
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/boundless-commerce-events-listener:latest
